### ISSUE TITLE
Empty States

### ISSUE THREAD

**Issue by Mike3563** [edenia/antelope-tools#1066]
We are going to add the function of presenting an empty states.
when I look for a block producer and there is no information to display

https://eos.antelope.tools/block-producers

![Image](https://user-images.githubusercontent.com/104119005/203449207-8346c311-41a5-4d65-ac81-e94973d25285.png)

You can find information in this link
https://www.toptal.com/designers/ux/empty-state-ux-design#:~:text=What%20are%20empty%20states%3F,common%20types%20of%20empty%20states.

**Comment by btcurenas** [comment]
![Image](https://user-images.githubusercontent.com/95376342/206026272-b7df469b-8da5-4a6d-9d85-f5df9fd09e1b.png)
