### ISSUE TITLE
Contract Not Showing Up

### ISSUE THREAD

**Issue by thenewlegend** [edenia/antelope-tools#1120]
**Describe the bug**
Tried the link "https://eos.antelope.tools/accounts?account=genesis.eden" but it doesn't work.

**To Reproduce**
1. Go to ' https://eos.antelope.tools/accounts?account=genesis.eden '
2. Click on ' Search'
3. See error

**Screenshots**
![IMG_20230113_123302_592](https://user-images.githubusercontent.com/63841336/212257903-cc5fb2f7-9e3f-4ff1-93b4-017ecf65b779.jpg)

**Smartphone (please complete the following information):**
- Device: [moto g31]
- OS: [Android 11]
- Browser [ Chrome]
- Version [108.0.5359.0]

**Additional context**
Tried different contracts too, Same result.

**Comment by xavier506** [comment]
@thenewlegend  can you please share the version of the APP you are using? its located in the footer of the page

<img width="334" alt="image" src="https://user-images.githubusercontent.com/5632966/212380915-f26c9f98-e74c-4f57-bbc9-629c372a8e05.png">

**Comment by thenewlegend** [comment]
It is the same , v 2.1.7 . Edgar replied that he got the result from another version. v2.1.3 if I remember correctly.

**Comment by Torresmorah** [comment]
@thenewlegend  Thanks for reporting the bug, I have checked it with the latest version and it works, but I realized that maybe the error you  were getting was related to the endpoints used to request the account data, and the message doesn't cover that situation.

So, I'm going to improve the error message to show when endpoints fail. 
Have you tried it again?

**Comment by thenewlegend** [comment]
Maybe it's because I am using a mobile device or the endpoint is always failing for me, it's the same result.  I'll wait for the merge and try again.
