### ISSUE TITLE
Didn't read chains.json correctly

### ISSUE THREAD

**Issue by EOS-Arabia** [edenia/antelope-tools#1161]
**Describe the bug**
In telos mainnet in the following path "https://telos.antelope.tools/undiscoverable-bps" , we are listed as "Undiscoverable Paid Block Producers"  , the tool searching for bp.json file but we have configured it in our chains.json as /telos.json.

**To Reproduce**
1. https://telos.antelope.tools/undiscoverable-bps
2. Check the BP.json link.
3. Check our chains.json from the following url:https://eosarabia.net/chains.json
4. here is our reg trx  https://explorer.telos.net/transaction/459cbf6436ce193f4bac5e8bb2f9398596fcd37b44c840d1cdf90851a9f70ffc

**Expected behavior**
Read the chains.json correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/47085785/220685528-17331c5c-9c73-48fc-8966-bb299d2fae65.png)
![image](https://user-images.githubusercontent.com/47085785/220685742-c4ab5868-ff4c-4eb2-be43-0d9f2fc920ec.png)

Thank you in advance ,

**Comment by maemultichain** [comment]
Hello EOS Arabia, we're going to review this information and reply you soon. Thanks for reporting.

**Comment by Torresmorah** [comment]
Hi EOS Arabia, thanks for reporting, we have checked that the logic to get the chains.json seems correct, on the other blockchain networks available in antelope tools where you are present the data is requested without problem.  

According to the health check we received a 403 Forbidden response code, do you have any limiters or other restrictions that may be denying the query to chains.json?
