### ISSUE TITLE
Ultra testnet faucet is not working

### ISSUE THREAD

**Issue by Torresmorah** [edenia/antelope-tools#1199]
**Describe the bug**
Nonexistent wallet error when issuing token in ultra testnet faucet.

**To Reproduce**
1. Go to https://ultra-testnet.antelope.tools/faucet
2. Complete the Issue Tokens with an account
3. Click on Get tokens

**Expected behavior**
The app show a message with the executed transaction.

**Screenshots**
![imagen](https://github.com/edenia/antelope-tools/assets/66583677/011a27c6-1967-4769-8814-d636fa2b9aff)

**Comment by leisterfrancisco** [comment]
Did the pods restart?

**Comment by xavier506** [comment]
![Image](https://github.com/edenia/antelope-tools/assets/5632966/97759c38-6548-4b56-9949-b82ec70af441)
