### ISSUE TITLE
Extend Network Usage Metrics

### ISSUE THREAD

**Issue by leisterfrancisco** [edenia/antelope-tools#1201]
create a new section called "stress test results"  new metrics in the Dashboard page to show the current state of the network, for example: 
- average cpu/net/ram used the last minute/hour/day/week/month
- cpu/net/ram used in certain block/transaction
- current load of the network (before entering into congestion mode)

<img width="1403" alt="Screenshot 2023-06-02 at 11 14 00" src="https://github.com/edenia/antelope-tools/assets/28828796/4638543b-37c3-435e-8ca4-a2730458104e">

**Comment by xavier506** [comment]
![image](https://github.com/edenia/antelope-tools/assets/5632966/453b9aa1-79b7-4cfe-a1b3-e4223cd51824)

**Comment by leisterfrancisco** [comment]
For example, would be nice to have something like this for every block producer, showing the total CPU, NET, ..., processed the last hour, things like that are very useful metrics:
<img width="585" alt="image" src="https://github.com/edenia/antelope-tools/assets/28828796/c37bb746-f93c-4134-b970-034259f94970">

**Comment by xavier506** [comment]
have historic data on TPS/APS (24 hours)?
