### ISSUE TITLE
Telos EVM Metrics

### ISSUE THREAD

**Issue by leisterfrancisco** [edenia/antelope-tools#1237]
# Add metrics to the Antelope Tools Dashboard for tEVM supporting
The tEVM improves on the EVM by implementing it’s own version of the EVM. Telos has implemented the original EVM as a smart contract on the tEVM. All activities that would normally be run by the EVM on an Ethereum node are run by a smart contract on the Telos blockchain. More info, [here](https://docs.telos.net/evm/about/introuction).

## Metrics
Creating new source of information will expand the usability of Antelope Tools not only based on AntelopeIO networks but also the extensions of the capabilities of the network, such as an EVM implementation, for example, [tEVM](https://docs.telos.net/evm/about/overview-and-architecture).

- [x] incoming `TLOS` total (box)
- [x] outgoing `TLOS` total (box)
- [x] incoming `TLOS` total (chart line - something similar to [coingecko](https://www.coingecko.com/en/coins/bitcoin))
- [x] outgoing `TLOS` total (chart line - something similar to [coingecko](https://www.coingecko.com/en/coins/bitcoin))

- [x] Last block - _pending to websockets_ (box).
- [x] Average block time. (box) (`tEVM = .5s`, `EOS EVM = 1s`)
- [x] Gas price. (box)
- [x] Average gas usage: Show to average gas usage in the last 30 transactions. (box)
- [x] Total wallets created. (box)
- [x] Average transactions per day (block and eosio.token -> ERC20). (box)
- [x] Daily transactions. (chart line)
- [x] ATH. (box)
- [x] RPC endpoints: Show endpoint, latency, health check. Reference: [Telos Health](https://www.teloscan.io/health) and [Chainlist](https://chainlist.org/?search=Telos&testnets=true).
<img width="946" alt="Screenshot 2023-07-11 at 20 41 57 2" src="https://github.com/edenia/antelope-tools/assets/28828796/de5a4cae-5056-4831-ad4e-0a791cbcc8bb">

## Support Content
[web3-examples.zip](https://github.com/edenia/antelope-tools/files/12030270/web3-examples.zip)

**Comment by Torresmorah** [comment]
https://github.com/edenia/antelope-tools/pull/1249
https://github.com/edenia/antelope-tools/pull/1256
https://github.com/edenia/antelope-tools/pull/1260
