### ISSUE TITLE
Include EOSRate.io ratings on BP info card

### ISSUE THREAD

**Issue by edgarithm** [edenia/antelope-tools#666]
Include the average rating of a BP on the BP info card displayed here https://mainnet.eosio.online/block-producers under stats

![image](https://user-images.githubusercontent.com/40245170/132570952-f9a8a5eb-1a9c-45eb-be85-53e4e10a6a3d.png)

**Comment by murillojorge** [comment]
https://zpl.io/V4NpAEy
<img width="482" alt="Screen Shot 2021-09-08 at 14 35 02" src="https://user-images.githubusercontent.com/1179619/132581537-9a0303e4-3b78-4db2-bdbf-d26bdde2202c.png">

**Comment by xavier506** [comment]
@AngeloCG97 created an API now on eos rate where data can be sourced from
