### ISSUE TITLE
Improve landing page

### ISSUE THREAD

**Issue by Edwinjrc** [edenia/antelope-tools#835]
The landing page can be confusing and could even seem unnecessary.
Links are not clear: Some of them do not seem different from the rest of the text.
Hierarchy needs to be strengthened in order to determine a clear call to action.
Check breakpoint related issues.
The footer needs a redesign.

**Comment by sanjayk0508** [comment]
Redesign the footer:
https://www.figma.com/file/c8STk9H3ZbJx5sF1aQeJPQ/eosio?node-id=0%3A1
