### ISSUE TITLE
Improve UI for nodes page

### ISSUE THREAD

**Issue by Mike3563** [edenia/antelope-tools#864]
Consolidate nodes by block producer into a single row. If a BP has a large number of nodes employ horizontal scroll.

Example:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/104119005/193665303-5d1fdaed-8aae-4318-8c63-9cba29432077.png">

- [ ] Consolidate information

**Comment by xavier506** [comment]
I like the idea of combining these three rows with node data into a single row 

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/5632966/192925158-37936341-e4e8-491f-9c18-2111417b1915.png">
