### ISSUE TITLE
Geo distribution map

### ISSUE THREAD

**Issue by Mike3563** [edenia/antelope-tools#977]
- [ ] Let's search and fix why right now is show wrong number of nodes in different contries

![Image](https://user-images.githubusercontent.com/104119005/203867296-ceaf1601-20cc-4e26-bb2a-d44351150fe6.png)

**Comment by xavier506** [comment]
Also the wrong number of nodes are displayed

for example on libre mainnet costa rica only has two nodes


![Image](https://user-images.githubusercontent.com/5632966/201262061-4378bcce-95eb-4544-a3b8-ffc20cb6b3b0.png)

**Comment by Torresmorah** [comment]
The search doesn't work

![Image](https://user-images.githubusercontent.com/66583677/207976564-6823f835-778a-49a0-b930-aa745a133394.png)
