### ISSUE TITLE
Update Open Source text to "Public Good"

### ISSUE THREAD

**Issue by xavier506** [edenia/antelope-tools#980]
Change This 

![Image](https://user-images.githubusercontent.com/5632966/196474536-a690f6d7-48e2-4885-92bb-4505027fb734.png)

For

`This App is a Community Public Good`
`Find out how to contribute`

**Comment by btcurenas** [comment]
Even inside this section
![image](https://user-images.githubusercontent.com/95376342/196479259-16690aac-5c73-4fe2-8404-57f5a030a87e.png)
